name: Build Docker Image

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ format('bettercollected/webapp:{0}', github.sha) }}
          build-args: |
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            SENTRY_RELEASE=${{ secrets.SENTRY_RELEASE }}
            SENTRY_URL=${{ secrets.SENTRY_URL }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_LOG_LEVEL=${{ secrets.SENTRY_LOG_LEVEL }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Executing remote ssh commands using ssh key and deploying
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SIRETO_BASTION_HOST }}
          username: ${{ secrets.SIRETO_BASTION_USERNAME }}
          key: ${{ secrets.SIRETO_BASTION_SSH_KEY }}
          port: ${{ secrets.SIRETO_BASTION_PORT }}
          script: |
            if [ ${{ github.ref }} == 'refs/heads/develop' ]; then
              docker --host=${{ secrets.DEV_DEPLOYMENT_HOST }} service update --image=bettercollected/webapp:${{ github.sha }} bettercollected-new_dev_webapp
            elif [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
              docker --host=${{ secrets.PROD_DEPLOYMENT_HOST }} service update --image=bettercollected/webapp:${{ github.sha }} bettercollected_webapp
            else
              echo "Deployment skipped for branch ${{ github.ref }}"
            fi
